{
    global:
        Plugify_*;
        HasPermission;
        HasGroup;
        GetImmunity;
        AddPermission;
        RemovePermission;
        AddGroup;
        RemoveGroup;
        GetCookie;
        SetCookie;
        CreateUser;
        DeleteUser;
        GetGroup;
        HasPermissionGroup;
        HasParentGroup;
        GetPriorityGroup;
        AddPermissionGroup;
        RemovePermissionGroup;
        CreateGroup;
        DeleteGroup;

    local: *;
};