context:
  name: plugify-plugin-permissions
  version: ${{ env.get("PACKAGE_VERSION") }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: .
  use_gitignore: false

build:
  number: 0
  string: ${{ target_platform | replace("-", "_") }}
  dynamic_linking:
    missing_dso_allowlist:
      - if: linux
        then:
          - "*/ld-linux*.so.*"
          - "*/libc.so.*"
          - "*/libm.so.*"
          - "*/libdl.so.*"
          - "*/libpthread.so.*"
          - "*/librt.so.*"

requirements:
  run:
    - if: linux
      then: __glibc >=2.17

about:
  homepage: https://github.com/${{ env.get("GITHUB_REPOSITORY", default="your-org/your-repo") }}
  license: MIT
  license_file: LICENSE
  summary: Permissions Plugin for Plugify
  description: |
    A plugin that provides a system to read and write configuration files.
  documentation: https://github.com/${{ env.get("GITHUB_REPOSITORY", default="your-org/your-repo") }}/blob/main/README.md
  repository: https://github.com/${{ env.get("GITHUB_REPOSITORY", default="your-org/your-repo") }}

extra:
  recipe-maintainers:
    - ${{ env.get("GITHUB_ACTOR", default="your-username") }}
